---
# API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gateway
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: ai-gateway
  template:
    metadata:
      labels:
        app: ai-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ai-gateway
          image: ghcr.io/prefeitura-rio/ai-gateway:stable
          command: ["/app/gateway"]
          envFrom:
            - secretRef:
                name: ai-gateway-secrets
          env:
            - name: SERVER_PORT
              value: "8000"
            - name: METRICS_PORT
              value: "8080"
            - name: GIN_MODE
              value: "release"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "json"
          resources:
            requests:
              ephemeral-storage: 500Mi
              cpu: 500m
              memory: 1Gi
            limits:
              ephemeral-storage: 2Gi
              cpu: 2000m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /live
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      restartPolicy: Always

---
# Message Workers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gateway-worker
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: ai-gateway-worker
  template:
    metadata:
      labels:
        app: ai-gateway-worker
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ai-gateway-worker
          image: ghcr.io/prefeitura-rio/ai-gateway:stable
          command: ["/app/worker"]
          envFrom:
            - secretRef:
                name: ai-gateway-secrets
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "json"
            - name: TRANSCRIBE_TEMP_DIR
              value: "/tmp/audio"
          volumeMounts:
            - name: temp-audio
              mountPath: /tmp/audio
          resources:
            requests:
              ephemeral-storage: 1Gi
              cpu: 250m
              memory: 128Mi
            limits:
              ephemeral-storage: 4Gi
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: temp-audio
          emptyDir: {}
      restartPolicy: Always

---
# API Gateway Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-gateway
  name: ai-gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ai-gateway

---
# Pod Disruption Budget for API
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-gateway-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-gateway

---
# Pod Disruption Budget for Workers
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-gateway-worker-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-gateway-worker

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-external-secret
      key: host
    - parameter: username
      name: rabbitmq-external-secret
      key: username
    - parameter: password
      name: rabbitmq-external-secret
      key: password
---
# Worker ScaledObject
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ai-gateway-worker-scaledobject
spec:
  scaleTargetRef:
    kind: Deployment
    name: ai-gateway-worker
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: rabbitmq
      metadata:
        protocol: http
        host: "http://rabbitmq.ai-gateway.svc.cluster.local:15672"
        queueName: user_messages
        mode: QueueLength
        value: "100"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn
