---
# API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eai-agent-gateway
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: eai-agent-gateway
  template:
    metadata:
      labels:
        app: eai-agent-gateway
    spec:
      automountServiceAccountToken: false
      containers:
        - name: eai-agent-gateway
          image: ghcr.io/prefeitura-rio/app-eai-agent-gateway:stable
          envFrom:
            - secretRef:
                name: eai-agent-gateway-secrets
          resources:
            requests:
              ephemeral-storage: 100Mi
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
          ports:
            - containerPort: 8000
              name: http
      restartPolicy: Always

---
# Worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eai-agent-gateway-worker
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: eai-agent-gateway-worker
  template:
    metadata:
      labels:
        app: eai-agent-gateway-worker
    spec:
      automountServiceAccountToken: false
      containers:
        - name: eai-agent-gateway-worker
          image: ghcr.io/prefeitura-rio/app-eai-agent-gateway:stable
          command: ["/bin/sh", "-c", "uv run celery -A src.queue.celery_app.celery worker --concurrency=${MAX_PARALLEL:-8} --loglevel=${CELERY_LOG_LEVEL:-info}"]
          envFrom:
            - secretRef:
                name: eai-agent-gateway-secrets
          resources:
            requests:
              ephemeral-storage: 100Mi
              cpu: 1000m
              memory: 4096Mi
            limits:
              cpu: 2000m
              memory: 4096Mi
      restartPolicy: Always

---
# Flower
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eai-agent-gateway-flower
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: eai-agent-gateway-flower
  template:
    metadata:
      labels:
        app: eai-agent-gateway-flower
    spec:
      automountServiceAccountToken: false
      containers:
        - name: eai-agent-gateway-flower
          image: ghcr.io/prefeitura-rio/app-eai-agent-gateway:stable
          command: ["/bin/sh", "-c", "uv run celery -A src.queue.celery_app.celery flower --port=${FLOWER_PORT:-5555}"]
          envFrom:
            - secretRef:
                name: eai-agent-gateway-secrets
          resources:
            requests:
              ephemeral-storage: 100Mi
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
      restartPolicy: Always

# ---
# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: eai-agent-gateway-scaled-object
# spec:
#   scaleTargetRef:
#     name: eai-agent-gateway
#   minReplicaCount: 1
#   maxReplicaCount: 10
#   cooldownPeriod: 10
#   triggers:
#     - type: prometheus
#       metadata:
#         serverAddress: http://prometheus.istio-system.svc.cluster.local:9090
#         metricName: http_requests_total
#         threshold: "4000"
#         query: sum(rate(istio_requests_total{destination_workload="eai-agent-gateway"}[1m]))

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eai-agent-gateway
  name: eai-agent-gateway
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8000
  selector:
    app: eai-agent-gateway

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eai-agent-gateway-flower
  name: eai-agent-gateway-flower
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    app: eai-agent-gateway-flower
